### PR TITLE
50 and 18

### PR DESCRIPTION
**Pull request by muffr**
Please let me know if I should create a pull request just for 18. Thanks.

### CODE REVIEW

**Comment by waynedyck** [comment]
Since both tickets are related it's fine to just combine them. In the future, could you create a more descriptive title for the merge request rather than, "50 and 18?" Something like, 'Creates new article content type, view and supporting Nodequeue." Thanks.

**Comment by waynedyck** [comment]
Unfortunately, I can't enable the feature without Drupal throwing SQL errors for some reason. Let's talk on Monday and I'd like to see how you created the content type and what you modified. Also not sure about the change surrounding the dependency switch from `views` to `date_views` in the "News View" feature entails.

**Comment by waynedyck** [comment]
I've got most of this working now.

* The reason for the errors was you modified `field_date` schema and there are two other content types, with existing content, which reference it.
* Nodequeues don't get exported with Features so I had to recreate it locally.
* Looks like the region contextual filter was removed as well in the `news_view` which we need to work properly on the region pages.

**Comment by muffr** [comment]
Hi, Wayne. Do you think the news content type (and others) would benefit from a separate publication date field? Do you want to filter the news view by month and year? I have it working thus locally in case you want to take a look. Thanks ☺

Ryan Muff
Interactive Communications
Washington State Department of Transportation
360.705.7712

**Comment by waynedyck** [comment]
I think, for the time being, I would rather keep it simple and just use the created date. We can use the date and year drop downs you added to the news view to apply the filtering.

**Comment by muffr** [comment]
Sounds good ☺

Ryan Muff
Interactive Communications
Washington State Department of Transportation
360.705.7712

**Pull request closed without merging**
